import { StatusBar } from 'expo-status-bar';
import { FlatList, StyleSheet, Text, View, Image, TouchableOpacity, Linking, Alert } from 'react-native';

const personagens = [
  {
    id: 1,
    nome: 'Cavaleiro',
    hp: '6(7)',
    def: '5(6)',
    mana: '180(200)',
    crtchan: '5',
    dmg: '4',
    spd: '6.5',
    armini: 'Pistola Velha',
    arminiimg: require('./assets/Bad_Pistol.png'),
    pass: 'Escudo Forte: Nenhum dano extra quando a armadura é quebrada.',
    imgpass: require('./assets/Buff_Strong_Shield.png'),
    img: require('./assets/Knight_0_art.png'),
    imgh1: require('./assets/Skill_Dual_Wield.png'),
    habilidade1tit: 'Empunhadura Dupla',
    habilidade1: 'Habilidade 1, Empunhadura Dupla: Duplica a arma atual nas duas mãos.',
    imgh2: require('./assets/Skill_Superior_Fire.png'),
    habilidade2tit: 'Disparos Superiores',
    habilidade2: 'Habilidade 2, Disparos Superiores: Usa ambas armas ao mesmo tempo, por um curto período de tempo.',
    imgh3: require('./assets/Skill_Chaotic_Strike.png'),
    habilidade3tit: 'Acerto Caótico',
    habilidade3: 'Habilidade 3, Acerto Caótico: Por um curto período de tempo, seus projéteis infligem um efeito aleatório nos alvos.'
  },
  {
    id: 2,
    nome: 'Guarda',
    hp: '5(6)',
    def: '3(4)',
    mana: '180(200)',
    crtchan: '10',
    dmg: '5',
    spd: '6.5',
    armini: 'João e Maria',
    arminiimg: require('./assets/Jack_and_Mary.png'),
    pass: 'Crítico Perfurante: Balas perfuram inimigos em acertos críticos.',
    imgpass: require('./assets/Buff_Piercing_Crit.png'),
    img: require('./assets/Rogue_0_art.png'),
    imgh1: require('./assets/Skill_Dodge.png'),
    habilidade1tit: 'Desvio',
    habilidade1: 'Habilidade 1, Desvio: Esquiva de ataques inimigos.',
    imgh2: require('./assets/Skill_Iaido.png'),
    habilidade2tit: 'Iaido',
    habilidade2: 'Habilidade 2, Iaido: Esquiva de ataques e corta inimigos, possui 3 cargas.',
    imgh3: require('./assets/Skill_Cartwheel.png'),
    habilidade3tit: 'Estrelinha',
    habilidade3: 'Habilidade 3, Estrelinha: Esquiva de ataques e causa dano de imapcto em inimigos ao segurar, realiza um corte giratório em volta de si ao soltar.'
  }, 
  {
    id: 3,
    nome: 'Bruxa',
    hp: '3(4)',
    def: '5(6)',
    mana: '240(260)',
    crtchan: '0',
    dmg: '3',
    spd: '6.5',
    armini: 'O Código',
    arminiimg: require('./assets/The_Code.png'),
    pass: 'Bastão Elemental: Projéteis elementais causam o dobro de dano em acertos críticos. Cajados causam dano aumentado.',
    imgpass: require('./assets/Buff_Elemental_Staff.png'),
    img: require('./assets/Witch_0_art.png'),
    imgh1: require('./assets/Skill_Lightning_Strike.png'),
    habilidade1tit: 'Golpe de Raio',
    habilidade1: 'Habilidade 1, Golpe de Raio: Lança um raio que causa dano e atordoa até 4 inimigos.',
    imgh2: require('./assets/Skill_Piercing_Frost.png'),
    habilidade2tit: 'Gelo Perfurante',
    habilidade2: 'Habilidade 2, Gelo Perfurante: Cria paredes de gelo que causa dano e bloqueiam projéteis.',
    imgh3: require('./assets/Skill_Firestorm.png'),
    habilidade3tit: 'Tempestade de Fogo',
    habilidade3: 'Habilidade 3, Tempestade de Fogo: Causa dano em uma grande área ao redor da personagem invocando 6 bolas de fogo.'
  }, 
  {
    id: 4,
    nome: 'Assasino',
    hp: '4(5)',
    def: '4(5)',
    mana: '180(200)',
    crtchan: '10',
    dmg: '5',
    spd: '7.5',
    armini: 'Lâmina Sangrenta',
    arminiimg: require('./assets/Blood_Blade.png'),
    pass: 'Refletir: Armas brancas refletem projéteis.',
    imgpass: require('./assets/Buff_Reflect.png'),
    img: require('./assets/Assassin_0_art.png'),
    imgh1: require('./assets/Skill_Dark_Blade.png'),
    habilidade1tit: 'Lâmina Sombria',
    habilidade1: 'Habilidade 1, Lâmina Sombria: Causa dano em uma linha à frente da personagem.',
    imgh2: require('./assets/Skill_Doppelganger.png'),
    habilidade2tit: 'Doppelgänger',
    habilidade2: 'Habilidade 2, Doppelgänger: Cria uma cópia da personagem que ataca os inimigos.',
    imgh3: require('./assets/Skill_Invisibility.png'),
    habilidade3tit: 'Invisibilidade',
    habilidade3: 'Habilidade 3, Invisibilidade: Torna-se invisível por um curto período de tempo, inimigos não conseguem te ver ou te atacar.'
  }, 
  {
    id: 5,
    nome: 'Alquimista',
    hp: '5(6)',
    def: '5(6)',
    mana: '180(200)',
    crtchan: '5',
    dmg: '4',
    spd: '6.5',
    armini: 'Máquina de Bolhas Dormentes',
    arminiimg: require('./assets/Dormant_Bubble_Machine.png'),
    pass: 'Resistência à Veneno: Garante imunidade a dano venenoso e redução de velocidade. Garante dano extra de veneno à inimigos.',
    imgpass: require('./assets/Buff_Poison.png'),
    img: require('./assets/Alchemist_0_art.png'),
    imgh1: require('./assets/Skill_Gas_Grenade.png'),
    habilidade1tit: 'Granada de Gás',
    habilidade1: 'Habilidade 1, Granada de Gás: Lança três granadas que criam nuvens venenosas, causando dano e redução de velocidade em inimigos dentro dela.',
    imgh2: require('./assets/Skill_Elemental_Potions.png'),
    habilidade2tit: 'Poções Elementais',
    habilidade2: 'Habilidade 2, Poções Elementais: Atira poções de gás/fogo/gelo nesta ordem alternativamente que causam dano em área, começando com 2 cargas.',
    imgh3: require('./assets/Skill_Concoction.png'),
    habilidade3tit: 'Concoção',
    habilidade3: 'Habilidade 3, Concoção: Cria uma poção que pode ser consumida para um efeito aleatório.'
  }, 
  {
    id: 6,
    nome: 'Engenheiro',
    hp: '5(6)',
    def: '5(6)',
    mana: '180(200)',
    crtchan: '5',
    dmg: '3',
    spd: '6.5',
    armini: 'H2O',
    arminiimg: require('./assets/H2O.png'),
    pass: 'Resistência à Fogo: Garante imunidade a dano de fogo e diminuição de dano de explosão. Garante dano extra de fogo à inimigos.',
    imgpass: require('./assets/Buff_Fire.png'),
    img: require('./assets/Engineer_0_art.png'),
    imgh1: require('./assets/Skill_Gun_Turret.png'),
    habilidade1tit: 'Torreta de Armas',
    habilidade1: 'Habilidade 1, Torreta de Armas: Implanta uma torreta que atira em inimigos próximos. Podem existir até 3 torretas ao mesmo tempo.',
    imgh2: require('./assets/Skill_Armor_Mount.png'),
    habilidade2tit: 'Armadura de Montaria',
    habilidade2: 'Habilidade 2, Armadura de Montaria: Temporariamente te equipa com uma armadura da fábrica.',
    imgh3: require('./assets/Skill_Interceptor.png'),
    habilidade3tit: 'Interceptor',
    habilidade3: 'Habilidade 3, Interceptor: Cria uma torreta que impede projéteis e ataca inimigos caso não aja projéteis por perto.'
  }, 
  {
    id: 7,
    nome: 'Vampiro',
    hp: '3(4)',
    def: '4(5)',
    mana: '120(140)',
    crtchan: '5',
    dmg: '3',
    spd: '6.5',
    armini: 'Taça de Vinho Carmesim',
    arminiimg: require('./assets/Crimson_Wine_Glass.png'),
    pass: 'Orbe de Vida: Inimigos tem a chance de dropar orbes que recuperam sua vida ao injeri-los.',
    imgpass: require('./assets/Buff_Health_Orb.png'),
    img: require('./assets/Vampire_0_art.png'),
    imgh1: require('./assets/Skill_Bat_Swarm.png'),
    habilidade1tit: 'Enxame de Morcegos',
    habilidade1: 'Habilidade 1, Enxame de Morcegos: Invoca um enxame de morcegos que ataca inimigos e recupera sua vida. Se sua vida estiver cheia, sua armadura ou sua mana é recuperada.',
    imgh2: require('./assets/Skill_Alien_Swirl.png'),
    habilidade2tit: 'Redemoinho Alienígena',
    habilidade2: 'Habilidade 2, Redemoinho Alienígena: Cria um redemoinho que atrai inimigos, causa dano e rouba vida.',
    imgh3: require('./assets/Skill_Immortal.png'),
    habilidade3tit: 'Imortal',
    habilidade3: 'Habilidade 3, Imortal: Por um curto período de tempo, converte todo dano recebido em vida. Caso sua vida esteja cheia, regenera sua mana ou adiciona vida extra até um máximo de +10 além de sua vida total.'
  },
  {
    id: 8,
    nome: 'Paladino',
    hp: '1(2)',
    def: '8(9)',
    mana: '120(140)',
    crtchan: '0',
    dmg: '4',
    spd: '6.5',
    armini: 'Mangual Sagrada',
    arminiimg: require('./assets/Sacred_Flail.png'),
    pass: 'Explosão Radial: Causa dano em uma área ao redor do personagem ao receber dano que quebraria sua armadura.',
    imgpass: require('./assets/Buff_Radial_Blast.png'),
    img: require('./assets/Paladin_0_art.png'),
    imgh1: require('./assets/Skill_Energy_Shield.png'),
    habilidade1tit: 'Escudo de Energia',
    habilidade1: 'Habilidade 1, Escudo de Energia: Cria um escudo que bloqueia projéteis.',
    imgh2: require('./assets/Skill_Holy_Warrior.png'),
    habilidade2tit: 'Guerreiro Sagrado',
    habilidade2: 'Habilidade 2, Guerreiro Sagrado: Temporariamente te equipa com uma espada gigante que dispara projéteis e destroi projéteis inimigos.',
    imgh3: require('./assets/Skill_Splash_And_Bash.png'),
    habilidade3tit: 'Pancada de Escudo',
    habilidade3: 'Habilidade 3, Pancada de Escudo: Recebe +2 de defesa enquanto o escudo estiver ativo, podendo liberar a habilidade para atirar o escudo e acertar inimigos à distância. O escudo regenera mana e armadura ao votlar.'
  },
  {
    id: 9,
    nome: 'Elfo',
    hp: '5(6)',
    def: '4(5)',
    mana: '180(200)',
    crtchan: '5',
    dmg: '4',
    spd: '6.5',
    armini: 'Arco Ancião',
    arminiimg: require('./assets/Ancient_Bow.png'),
    pass: 'Carga: Diminui o tempo de carregamento de armas que precisam de carregamento.',
    imgpass: require('./assets/Buff_Charge.png'),
    img: require('./assets/Elf_0_art.png'),
    imgh1: require('./assets/Skill_Focus_Fire.png'),
    habilidade1tit: 'Foco de Fogo',
    habilidade1: 'Habilidade 1, Foco de Fogo: Automaticamente mira em inimigos e dispara 3 flechas mágicas.',
    imgh2: require('./assets/Skill_Arrow_Rain.png'),
    habilidade2tit: 'Chuva de Flechas',
    habilidade2: 'Habilidade 2, Chuva de Flechas: Dispara uma chuva de flechas que causa dano em área.',
    imgh3: require('./assets/Skill_Guardian_Elf.png'),
    habilidade3tit: 'Elfo Guardião',
    habilidade3: 'Habilidade 3, Elfo Guardião: Sumona um elfo guardião de um elemento entre fogo, gelo e ar para te auxiliar em combate.'
  },
  {
    id: 10,
    nome: 'Lobisomem',
    hp: '11(12)',
    def: '1(2)',
    mana: '120(140)',
    crtchan: '5',
    dmg: '5',
    spd: '6.5',
    armini: 'Garras Flamejantes',
    arminiimg: require('./assets/Flaring_Claw.png'),
    pass: 'Resistência à armadilhas: Garante imunidade a dano de armadilhas e dano de colisão.',
    imgpass: require('./assets/Buff_Trap.png'),
    img: require('./assets/Werewolf_0_art.png'),
    imgh1: require('./assets/Skill_Berserk.png'),
    habilidade1tit: 'Berserk',
    habilidade1: 'Habilidade 1, Berserk: Quanto menor sua vida, maior sua velocidade de ataque por um curto período de tempo.',
    imgh2: require('./assets/Skill_Blood_Thirst.png'),
    habilidade2tit: 'Sede de Sangue',
    habilidade2: 'Habilidade 2, Sede de Sangue: Ataca 4 vezes com as garras e recupera vida.',
    imgh3: require('./assets/Skill_Devour.png'),
    habilidade3tit: 'Devorar',
    habilidade3: 'Habilidade 3, Devorar: Devora um inimigo para recuperar vida e mana.'
  },
  {
    id: 11,
    nome: 'Sacerdotisa',
    hp: '3(4)',
    def: '5(6)',
    mana: '200(220)',
    crtchan: '0',
    dmg: '3',
    spd: '6.5',
    armini: 'Cruz de Madeira',
    arminiimg: require('./assets/Wooden_Cross.png'),
    pass: 'Eficácia de Poção: Poções de cura recuperam mais pontos de vida.',
    imgpass: require('./assets/Buff_Potion_Effectiveness.png'),
    img: require('./assets/Priestess_0_art.png'),
    imgh1: require('./assets/Skill_Regeneration_Pact.png'),
    habilidade1tit: 'Pacto de Regeneração',
    habilidade1: 'Habilidade 1, Pacto de Regeneração: Cria uma área de cura para aliados e si mesmo por um curto período de tempo e concede escudo extra.',
    imgh2: require('./assets/Skill_Pray.png'),
    habilidade2tit: 'Rezar',
    habilidade2: 'Habilidade 2, Rezar: Cura seres amigáveis em volta e concede aumento de velocidade de ataque e de movimento.',
    imgh3: require('./assets/Skill_Moon_Shadow.png'),
    habilidade3tit: 'Sombra da Lua',
    habilidade3: 'Habilidade 3, Sombra da Lua: Invoca mísseis da lua e das sombras para curar aliados e queimar inimigos.'
  },
  {
    id: 12,
    nome: 'Druida',
    hp: '6(7)',
    def: '3(4)',
    mana: '130(150)',
    crtchan: '5',
    dmg: '5',
    spd: '6.5',
    armini: 'Osso Crocante',
    arminiimg: require('./assets/Crispy_Bone.png'),
    pass: 'Familiares: Aumenta os atributos de pets e companheiros.',
    imgpass: require('./assets/Buff_Pet.png'),
    img: require('./assets/Druid_0_art.png'),
    imgh1: require('./assets/Skill_Frostfire_Wolves.png'),
    habilidade1tit: 'Lobos de Gelo e Fogo',
    habilidade1: 'Habilidade 1, Lobos de Gelo e Fogo: Invoca lobos de gelo e fogo que atacam inimigos. Lobos de gelo causam dano aumentado em inimigos congelados e lobos de fogo causam dano aumentado em inimigos queimados.',
    imgh2: require('./assets/Skill_Venom_Vines.png'),
    habilidade2tit: 'Vinhas Venenosas',
    habilidade2: 'Habilidade 2, Vinhas Venenosas: Invoca vinhas que causam dano venenoso e bloqueiam projéteis.',
    imgh3: require('./assets/Skill_Fuzzy_Bear.png'),
    habilidade3tit: 'Urso Felpudo',
    habilidade3: 'Habilidade 3, Urso Felpudo: Invoca um urso montaria que ataca inimigos por perto e te protege de ataques.'
  },
  {
    id: 13,
    nome: 'Robot',
    hp: '3(4)',
    def: '6(7)',
    mana: '180(200)',
    crtchan: '0',
    dmg: '3',
    spd: '6.5',
    armini: 'Canhão Flutuante de Satélite',
    arminiimg: require('./assets/Satellite_Floating_Gun.png'),
    pass: 'Laser: Aumenta o raio de armas de dano de lase e garante imunidade e a dano elétrico.',
    imgpass: require('./assets/Buff_Laser.png'),
    img: require('./assets/Robot_0_art.png'),
    imgh1: require('./assets/Skill_Electric_Overload.png'),
    habilidade1tit: 'Sobrecarga Elétrica',
    habilidade1: 'Habilidade 1, Sobrecarga Elétrica: Causa dano elétrico em inimigos próximos e atordoa-los.',
    imgh2: require('./assets/Skill_Drone_Swarm.png'),
    habilidade2tit: 'Enxame de Drones',
    habilidade2: 'Habilidade 2, Enxame de Drones: Invoca um enxame de drones que ataca inimigos por perto.',
    imgh3: require('./assets/Skill_EMP.png'),
    habilidade3tit: 'Pulso Eletromagnético',
    habilidade3: 'Habilidade 3, Pulso Eletromagnético: Causa dano elétrico em inimigos próximos e desativa suas habilidades por um curto período de tempo.'
  },
  {
    id: 14,
    nome: 'Berserker',
    hp: '9(10)',
    def: '3(4)',
    mana: '150(170)',
    crtchan: '5',
    dmg: '5',
    spd: '6.5',
    armini: 'Luvas de Boxe',
    arminiimg: require('./assets/Boxing_Gloves.png'),
    pass: 'Cadência de tiros: Aumenta a velocidade de ataque de todas as armas.',
    imgpass: require('./assets/Buff_Fire_Rate.png'),
    img: require('./assets/Berserker_0_art.png'),
    imgh1: require('./assets/Skill_Rage.png'),
    habilidade1tit: 'Fúria',
    habilidade1: 'Habilidade 1, Fúria: Reduz a cadência de ataque para meio segundo com qualquer arma.',
    imgh2: require('./assets/Skill_Free_Style.png'),
    habilidade2tit: 'Estilo Livre',
    habilidade2: 'Habilidade 2, Estilo Livre: Cria três cópias que atacam pelo Berserker por um curto período de tempo.',
    imgh3: require('./assets/Skill_Leap.png'),
    habilidade3tit: 'Salto',
    habilidade3: 'Habilidade 3, Salto: Pula sobre inimigos e objetos, causando dano em área.'
  },
  {
    id: 15,
    nome: 'Necromante',
    hp: '3(4)',
    def: '5(6)',
    mana: '240(260)',
    crtchan: '0',
    dmg: '4',
    spd: '6.5',
    armini: 'Cajado da Praga',
    arminiimg: require('./assets/Staff_of_Plague.png'),
    pass: 'Desacelerar Balas: Projéteis inimigos são desacelerados.',
    imgpass: require('./assets/Buff_Slow_Bullet.png'),
    img: require('./assets/Necromancer_0_art.png'),
    imgh1: require('./assets/Skill_Nightmare.png'),
    habilidade1tit: 'Pesadelo',
    habilidade1: 'Habilidade 1, Pesadelo: Marca um inimigo que, ao derrotado, invoca um fantasma que luta por você.',
    imgh2: require('./assets/Skill_Omen_Stone.png'),
    habilidade2tit: 'Pedra do Presságio',
    habilidade2: 'Habilidade 2, Pedra do Presságio: Sumona um meteoro que causa dano em área e cria aranhas da praga para te auxiliar em combate.',
    imgh3: require('./assets/Skill_Souls_Resurrect.png'),
    habilidade3tit: 'Ressurreição das Almas',
    habilidade3: 'Habilidade 3, Ressurreição das Almas: Resurrecta monstros mortos para lutar ao seu lado.'
  },
  {
    id: 16,
    nome: 'Caçador de Recompensas',
    hp: '5(6)',
    def: '5(6)',
    mana: '180(200)',
    crtchan: '5',
    dmg: '4',
    spd: '6.5',
    armini: 'Nemesis dos Vilões',
    arminiimg: require('./assets/Nemesis_of_Villains.png'),
    pass: 'Combos: Aumenta o combo de armas com combos.',
    imgpass: require('./assets/Buff_Combo.png'),
    img: require('./assets/Officer_0_art.png'),
    imgh1: require('./assets/Skill_Gun_Spin.png'),
    habilidade1tit: 'Giro de Arma',
    habilidade1: 'Habilidade 1, Giro de Arma: Recebe um revólver com 6 balas que te garante bônus em dano e velocidade de ataque por um curto período de tempo ao derrotar 3 inimigos com a arma.',
    imgh2: require('./assets/Skill_Bounty_Tag.png'),
    habilidade2tit: 'Etiqueta de Recompensa',
    habilidade2: 'Habilidade 2, Etiqueta de Recompensa: Marca um inimigo que, ao ser derrotado, dropa moedas e passa a marca para outro inimigo.',
    imgh3: require('./assets/Skill_Close_Air_Support.png'),
    habilidade3tit: 'Suporte Aéreo Próximo',
    habilidade3: 'Habilidade 3, Suporte Aéreo Próximo: Invoca um ataque aéreo que bombardeia inimigos próximos.'
  },
  {
    id: 17,
    nome: 'Taoísta',
    hp: '4(5)',
    def: '4(5)',
    mana: '180(200)',
    crtchan: '5',
    dmg: '4',
    spd: '6.5',
    armini: 'Espada de Tao',
    arminiimg: require('./assets/Tao_Sword.png'),
    pass: 'Artes de Tao: A arma secundária se torna uma arma sensciente e flutuante que ataca sozinha.',
    imgpass: require('./assets/Buff_Tao_Arts.png'),
    img: require('./assets/Taoist_0_art.png'),
    imgh1: require('./assets/Skill_Genesis_of_Swords.png'),
    habilidade1tit: 'Gênesis de Espadas',
    habilidade1: 'Habilidade 1, Gênesis de Espadas: Invoca 7 espadas que atacam inimigos em volta.',
    imgh2: require('./assets/Skill_Bagua.png'),
    habilidade2tit: 'Bagua',
    habilidade2: 'Habilidade 2, Bagua: Cria um campo de energia que reflete projéteis inimigos.',
    imgh3: require('./assets/Skill_Sword_Fly.png'),
    habilidade3tit: 'Voo da Espada',
    habilidade3: 'Habilidade 3, Voo da Espada: Invoca uma espada que serve de montaria para você.'
  },
  {
    id: 18,
    nome: 'Dobrador de Ar',
    hp: '4(5)',
    def: '6(7)',
    mana: '160(180)',
    crtchan: '15',
    dmg: '5',
    spd: '6.5',
    armini: 'Soco Qian-Kun',
    arminiimg: require('./assets/Qian-kun_Punch.png'),
    pass: 'Melhor Soco Qian-Kun: O ataque desarmado do Dobrador de Ar causa 3 instâncias consecutivas de dano e libera uma onda de Qi-gong em formato de cone, que inflige dano em área.',
    imgpass: require('./assets/Buff_Qian-kun_Punch.png'),
    img: require('./assets/Airbender_0_art.png'),
    imgh1: require('./assets/Skill_Pulsating_Blow.png'),
    habilidade1tit: 'Golpe Pulsante',
    habilidade1: 'Habilidade 1, Golpe Pulsante: Causa dano em área com um golpe poderoso.',
    imgh2: require('./assets/Skill_Orbiting_Stars.png'),
    habilidade2tit: 'Estrelas Orbitantes',
    habilidade2: 'Habilidade 2, Estrelas Orbitantes: Absorve projéteis inimigos e os devolve com mais força.',
    imgh3: require('./assets/Skill_Meridian_Sword.png'),
    habilidade3tit: 'Meridiano da Espada',
    habilidade3: 'Habilidade 3, Meridiano da Espada: Suas armas liberam energia qi-gong ao atacar.'
  },
  {
    id: 19,
    nome: 'Demonomante',
    hp: '4(5)',
    def: '5(6)',
    mana: '213(233)',
    crtchan: '0',
    dmg: '4',
    spd: '6.5',
    armini: 'Chave da Estrela Fraca',
    arminiimg: require('./assets/Key_of_the_Faint_Star.png'),
    pass: 'Diabrete Feroz: Invoca um diabrete ao matar inimigos que bloqueia danos.',
    imgpass: require('./assets/Buff_Fiery_Imp.png'),
    img: require('./assets/Demonmancer_0_art.png'),
    imgh1: require('./assets/Skill_Amiis_Burning_Body.png'),
    habilidade1tit: 'Corpo em Chamas de Amiis',
    habilidade1: 'Habilidade 1, Corpo em Chamas de Amiis: Causa dano em área ao redor do personagem e deixa inimigos queimando, podendo sacrificar diabretes para aumentar o dano.',
    imgh2: require('./assets/Skill_Helping_Hand_Eligos.png'),
    habilidade2tit: 'Mão Ajudante de Eligos',
    habilidade2: 'Habilidade 2, Mão Ajudante de Eligos: Invoca uma mão gigante que ataca inimigos e bloqueia projéteis.',
    imgh3: require('./assets/Skill_Amons_Protection.png'),
    habilidade3tit: 'Proteção de Amon',
    habilidade3: 'Habilidade 3, Proteção de Amon: Cria um escudo que absorve danos e restaura vida.'
  },
  {
    id: 20,
    nome: 'Mineradora',
    hp: '5(6)',
    def: '4(5)',
    mana: '180(200)',
    crtchan: '5',
    dmg: '4',
    spd: '6.5',
    armini: 'Picareta',
    arminiimg: require('./assets/Pickaxe.png'),
    pass: 'Armadura de Ouro: À cada 100 moedas consigo, você ganha +1 de defesa.',
    imgpass: require('./assets/Buff_Gold_Armor.png'),
    img: require('./assets/Miner_0_art.png'),
    imgh1: require('./assets/Skill_Underground_Operations.png'),
    habilidade1tit: 'Operações Subterrâneas',
    habilidade1: 'Habilidade 1, Operações Subterrâneas: Permite movimentar-se rapidamente sob a superfície e causar dano em área ao voltar.',
    imgh2: require('./assets/Skill_Cart_Delivery.png'),
    habilidade2tit: 'Entrega de Carrinho',
    habilidade2: 'Habilidade 2, Entrega de Carrinho: Permite transportar itens e personagens rapidamente.',
    imgh3: require('./assets/Skill_Sandworm_Storm.png'),
    habilidade3tit: 'Tempestade de Verme de Areia',
    habilidade3: 'Habilidade 3, Tempestade de Verme de Areia: Invoca uma tempestade de vermes de areia que causa dano em área e atordoa inimigos.'
  },
  {
    id: 21,
    nome: 'Mestre das Armadilhas',
    hp: '5(6)',
    def: '5(6)',
    mana: '200(220)',
    crtchan: '0',
    dmg: '4',
    spd: '6',
    armini: 'Arma de Gancho',
    arminiimg: require('./assets/Grappling_Gun.png'),
    pass: 'Bomba Secreta: Monstros tem chance de explodirem ao morrer.',
    imgpass: require('./assets/Buff_Monster_Explode.png'),
    img: require('./assets/Trap_Master_0_art.png'),
    imgh1: require('./assets/Skill_Telecontrolled_Bomb.png'),
    habilidade1tit: 'Bomba Telecontrolada',
    habilidade1: 'Habilidade 1, Bomba Telecontrolada: Lança multiplas bombas que podem ser detonadas manualmente para causar dano em área.',
    imgh2: require('./assets/Skill_Masters_Trick.png'),
    habilidade2tit: 'Truque de Mestre',
    habilidade2: 'Habilidade 2, Truque de Mestre: Invoca uma armadilha que atrai inimigos enquanto o Mestre das Armadilhas se esconde e regenera mana.',
    imgh3: require('./assets/Skill_Hat_Trick.png'),
    habilidade3tit: 'Truque de Cartola',
    habilidade3: 'Habilidade 3, Truque de Cartola: Atira sua cartola no chão e invoca várias pombas brancas que atacam inimigos aleatórios.'
  },
  {
    id: 22,
    nome: 'Príncipe de Fantasia',
    hp: '3(4)',
    def: '4(5)',
    mana: '220(270)',
    crtchan: '3',
    dmg: '4',
    spd: '7',
    armini: 'Arma Mucosa de Plástico',
    arminiimg: require('./assets/Plastic_Mucus_Gun.png'),
    pass: 'Poças Elementais: Aumenta a área de efeito de poças elementais e garante imunidade a seus efeitos.',
    imgpass: require('./assets/Buff_Elemental_Pool.png'),
    img: require('./assets/Costume_Prince_0_art.png'),
    imgh1: require('./assets/Skill_Transform21.png'),
    habilidade1tit: 'Transforme! Rei Slime!',
    habilidade1: 'Habilidade 1, Transforme! Rei Slime!: Transforma-se em um rei slime gigante que causa dano em área e dispara projéteis.',
    imgh2: require('./assets/Skill_Forward21.png'),
    habilidade2tit: 'Avante! Rei Carangueijo de Cristal!',
    habilidade2: 'Habilidade 2, Avante! Rei Carangueijo de Cristal!: Transforma-se em um rei carangueijo de cristal que atira projéteis e reflete projéteis inimigos.',
    imgh3: require('./assets/Skill_Manifest21.png'),
    habilidade3tit: 'Manifeste! Rei Violeta!',
    habilidade3: 'Habilidade 3, Manifeste! Rei Violeta!: Transforma-se em um rei violeta que ataca inimigos por perto e regenera vida.'
  }
];

export default function App() {

  const criaItem = ({ item }) => (
    <TouchableOpacity 
      style={styles.listaItem} 
      onPress={() => 
        Alert.alert(
          'Habilidades de ' + item.nome, 
          item.habilidade1 + '\n\n' + item.habilidade2 + '\n\n' + item.habilidade3
        )
      }
    >
      <Image source={item.img} style={styles.listaImagem} />

      <View style={styles.listaDetalhes}>
        
        <Text style={styles.textoForte}>Nome: <Text style={styles.textoNormal}>{item.nome}</Text></Text>
        <Text style={styles.textoForte}><Image source={require('./assets/Health_Icon.png')} style={{width: 20, height: 17}}/> HP: <Text style={styles.textoNormal}>{item.hp}</Text></Text>
        <Text style={styles.textoForte}><Image source={require('./assets/Armor_Icon.png')} style={{width: 16, height: 20}}/> Defesa: <Text style={styles.textoNormal}>{item.def}</Text></Text>
        <Text style={styles.textoForte}><Image source={require('./assets/Energy_Icon.png')} style={{width: 18, height: 18}}/> Mana: <Text style={styles.textoNormal}>{item.mana}</Text></Text>
        <Text style={styles.textoForte}><Image source={require('./assets/Critical_Chance_Icon.png')} style={{width: 20, height: 17}}/> Chance de Crítico: <Text style={styles.textoNormal}>{item.crtchan}%</Text></Text>
        <Text style={styles.textoForte}><Image source={require('./assets/Damage_Icon.png')} style={{width: 11, height: 20}}/> Dano Desarmado: <Text style={styles.textoNormal}>{item.dmg}</Text></Text>
        <Text style={styles.textoForte}><Image source={require('./assets/Movement_Speed_Icon.png')} style={{width: 20, height: 13}}/> Velocidade: <Text style={styles.textoNormal}>{item.spd}</Text></Text>
        <Text style={styles.textoForte}><Image source={item.arminiimg} style={styles.habilidadeimagem}/> Arma Inicial: <Text style={styles.textoNormal}>{item.armini}</Text></Text>
        <Text style={styles.textoForte}><Image source={item.imgpass} style={styles.habilidadeimagem}/> Passiva - <Text style={styles.textoNormal}>{item.pass}</Text></Text>
        <Text style={styles.textoForte}><Image source={item.imgh1} style={styles.habilidadeimagem}/> Habilidade 1: <Text style={styles.textoNormal}>{item.habilidade1tit}</Text></Text>
        <Text style={styles.textoForte}><Image source={item.imgh2} style={styles.habilidadeimagem}/> Habilidade 2: <Text style={styles.textoNormal}>{item.habilidade2tit}</Text></Text>
        <Text style={styles.textoForte}><Image source={item.imgh3} style={styles.habilidadeimagem}/> Habilidade 3: <Text style={styles.textoNormal}>{item.habilidade3tit}</Text></Text>
      </View>


    </TouchableOpacity>
  );

  return (
    <View style={styles.container}>
      <StatusBar style="auto"/>
      <Text style={styles.titulo}>Escolha seu Personagem</Text>

      <FlatList 
        data={personagens} 
        renderItem={criaItem} 
        keyExtractor={item => item.id.toString()} 
        showsVerticalScrollIndicator={false} 
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#181818',
    paddingTop: 50,
    paddingHorizontal: 10,
  },
  titulo: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#e24343',
    textAlign: 'center',
  },
  listaItem: {
    backgroundColor: '#5a4747',
    marginBottom: 15,
    padding: 15,
    borderRadius: 15,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 3,
  },
  listaImagem: {
    width: 60,
    height: 90,
    borderRadius: 8,
  },
  habilidadeimagem: {
    width: 45,
    height: 45,
    justifyContent: 'center',
    borderRadius: 3,
  },
  listaDetalhes: {
    marginLeft: 15,
    flex: 1,
  },
  textoForte: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#b1b1b1',
  },
  textoNormal: {
    fontWeight: 'normal',
    color: '#e7e7e7',
  }
});